name: Run tests
on:
  pull_request:
jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential cmake libsfml-dev

      - name: Compile
        run: |
          mkdir build
          cd build
          cmake ..
          make
          cd ..
